### ISSUE TITLE
[ISSUE] Sherlock stops after Countable search

### ISSUE THREAD

**Issue by Kaisarion** [sherlock-project/sherlock#1305]
- [X] I'm reporting a bug in Sherlock's functionality
- [X] The bug I'm reporting is not a false positive or a false negative
- [X] I've verified that I'm running the latest version of Sherlock
- [X] I've checked for similar bug reports including closed ones
- [X] I've checked for pull requests that attempt to fix this bug

## Description
Upon running `python3 sherlock username`, the checks stop right after a return on Countable. (See screenshot below)
As I am unsure of if this is a social media downtime issue, I am consulting here.
<img width="401" alt="Screen_Shot_2022-04-16_at_11 00 42_PM" src="https://user-images.githubusercontent.com/60671860/163698401-dd7c35e0-b6ec-468c-9b9d-6ac29806065c.png">

Suggested fix:
Improve 404 messages and insert timeouts if sites are not reachable within a few seconds.

**Comment by sdushantha** [comment]
It seems like it is not an issue with Countable. It is an issue with Designspiration. This is evident because when you run `python3 sherlock krimsies --print-all`, you will see that Sherlock hangs a little after DailyMotion:
![image](https://user-images.githubusercontent.com/27065646/163722557-fa11e864-e1ae-4738-ac7a-e6da55913cd3.png)

If we check the `data.json` file, we can see the next site that is being checked is Designsipiration. Upon visiting their homepage, you'll notice that the site seems to be taking a long time to load.
![image](https://user-images.githubusercontent.com/27065646/163722645-a254f063-0e16-47fd-adf4-ade1788e6031.png)

We will fix this by removing Designsipration from Sherlock :+1: 


Just so you know, we do have an option to set time outs:
```
  --timeout TIMEOUT     Time (in seconds) to wait for response to requests.
                        Default timeout is infinity. A longer timeout will be
                        more likely to get results from slow sites. On the
                        other hand, this may cause a long delay to gather all
                        results.
```
