### ISSUE TITLE
Usernames starting with hyphens

### ISSUE THREAD

**Issue by TheUnsocialEngineer** [sherlock-project/sherlock#1375]
## Checklist

- [x ] I'm reporting a bug in Sherlock's functionality
- [x ] The bug I'm reporting is not a false positive or a false negative
- [ x] I've verified that I'm running the latest version of Sherlock
- [ x] I've checked for similar bug reports including closed ones
- [x ] I've checked for pull requests that attempt to fix this bug

## Description

Sherlock can't search usernames starting with a hyphen as it clashes with args. Tried to include username in single and double quotes however this also didn't fix the issue. Using Sherlock 
"0.14.0"

**Comment by Fwishys** [comment]
Just to add something, this also goes with any type of "special character", for example (name), name., and name,,

**Comment by Shubhpro** [comment]
bro try this.username ("username.py
")

**Comment by tjhasan** [comment]
I tested with any type of special character as @Fwishys mentioned, and they seem to work fine so long as you encase them in quotations. For example (name) will make powershell or terminal throw an error, but '(name)' will make it work with no issues. 

The only special case is with hyphens in that, in order to make it work with hyphens, you need to have an extra whitespace character before the hyphen. So '-name' won't work, but ' -name' will.

Read [here](https://github.com/sherlock-project/sherlock/pull/1407) and [here](https://bugs.python.org/issue9334) to see why. TL:DR, it's a bug that no one seems to want to fix?

I created a pull request that allows Sherlock to search usernames starting with hyphens. I've also added some wording that specifies this in the -h screen.
