### ISSUE TITLE
Use Internet archive to get deep web results

### ISSUE THREAD

**Issue by sam5epi0l** [sherlock-project/sherlock#1393]
## Checklist

- [x] I'm reporting a feature request
- [x] I've checked for similar feature requests including closed ones

## Description

# With [Internet Archive](https://archive.org/web/) (Wayback Machine) we can get even more results (deleted users, dead urls, private/public, etc.)

<img src="https://raw.githubusercontent.com/sam5epi0l/sam5epi0l.github.io/main/sherlock_with_wayback_mindmap.jpg">

**Comment by sweezyio** [comment]
The Internet Archive, because it relies on the page having previously been saved to the archive, isn't a reliable test for this. 

There would be no way of knowing whether a username just didn't exist then or if the Archive just doesn't have a copy, leading to false negatives. Plus, sending hundreds of requests to the IA's already strained infrastructure for username detection doesn't seem like a good idea.

**Comment by sdushantha** [comment]
This is a great idea but at the moment this is not a feature we would like to add to Sherlock
