### ISSUE TITLE
Missing TikTok results

### ISSUE THREAD

**Issue by TVikg** [sherlock-project/sherlock#1611]
- [X ] I'm reporting a bug in Sherlock's functionality
- [ X] The bug I'm reporting is not a false positive or a false negative
- [ X] I've verified that I'm running the latest version of Sherlock
- [ X] I've checked for similar bug reports including closed ones
- [ X] I've checked for pull requests that attempt to fix this bug

WRITE DESCRIPTION HERE

Using the last version of sherlock the search for TikTok users is missing.

**Comment by magicmicah** [comment]
Looks like the issue is a timeout problem where python/requests is getting caught by Tiktok's load balancer and timing out. Not sure of a clever way around it just using requests. It might be possible using a proxy server or even selenium. Some more info on that here: https://medium.com/analytics-vidhya/the-art-of-not-getting-blocked-how-i-used-selenium-python-to-scrape-facebook-and-tiktok-fd6b31dbe85f

**Comment by sdushantha** [comment]
It has been added here:

https://github.com/sherlock-project/sherlock/blob/dc4e4c3571a60d4250783d786037151c5589e317/sherlock/resources/data.json#L1798-L1802
