### ISSUE TITLE
Multinames searcher

### ISSUE THREAD

**Issue by craciu25yt** [sherlock-project/sherlock#1624]
## Checklist

- [ x ] I'm reporting a feature request
- [ x ] I've checked for similar feature requests including closed ones

## Description

Add a system for multi names checks. For example, if I have the nick `craciu25_YT`, try to find `craciu25yt`, `craciu26yt`, `craciuyt`...
That can add like the double or more of time but it will be a very good feature

**Comment by shvms** [comment]
How to do you define other usernames from the one that you input? Do you input all multiple usernames yourself or you want the software to search for these similar names, that is, stemming out of the root username you provided?

**Comment by craciu25yt** [comment]
I mean that the software try similar usernames

**Comment by a-r-r-o-w** [comment]
I think what you would like is a wordlist generator that can generate a list of similar usernames, that you can then provide to sherlock for search (sherlock can take multiple usernames as input. You could also run parallel instances as well as combine the multiple username input feature to get results faster). Try out the following tools and see if they match your expected behaviour:

- [pydictor](https://github.com/LandGrey/pydictor)
- [bopscrk](https://github.com/r3nt0n/bopscrk)
- [cook](https://github.com/glitchedgitz/cook)

That said, I don't believe this feature is a good fit for sherlock because the primary goal with it is to search for a given username opposed to finding similar profiles that match the query username.

**Comment by sdushantha** [comment]
Great idea! But at the moment we don't need a feature like this. A rewrite of Sherlock is work in progress so we might add this feature in the new version
