### ISSUE TITLE
i installed sherlock and it said somethings is wrong, can somebody help me??

### ISSUE THREAD

**Issue by krma12** [sherlock-project/sherlock#1631]
$ python3 -m pip install -r requirements.txt                                
Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'

**Comment by recleun** [comment]
@krma12 I think you didn't install it properly. You should first clone the repository with the following command:

`git clone https://github.com/sherlock-project/sherlock.git`

If you don't have git installed then you can either install it or you can download the repository as .zip, then you should go to the location of the repository that you just cloned. You can do that by using the command `cd` (replace folder name here with the name of the folder that contains the repository):

`cd {folder name here}`

Then you can use the following command to download the dependencies of sherlock. It should work now since python didn't find `requirements.txt`, and it exists inside the repository, that's why I think you didn't install clone the repository properly.

`python3 -m pip install -r requirements.txt`
