### ISSUE TITLE
Facebook account hack 

### ISSUE THREAD

**Issue by mrbhargabdas** [sherlock-project/sherlock#1671]
## Checklist

- [ ] I'm reporting a feature request
- [ ] I've checked for similar feature requests including closed ones

## Description

WRITE DESCRIPTION HERE

**Comment by mrbhargabdas** [comment]
I need a help for how to hack a facebook account easily

**Comment by el2zay** [comment]
welcome in 2014

**Comment by Superlegend717** [comment]
Please i am a learner i need to know how can i operate termux by using an android phone.

**Comment by el2zay** [comment]
Sure tell us

**Comment by luisaglez1** [comment]
I wanted to[ hack Facebook ](https://hackfreeonline.com/facebook/
)easily so if you want to know a person's tastes, secrets, music, books, age, nationality, last names, photos, videos and everything related to this, this is why what you need to hack Facebook is a good program like the one I am recommending to you so that from this you only have to perform the procedure that is requested and like me you can take that next step but do it safely and confidently just like I did and to be able to obtain the results that I obtained and in the best way, so for what follows you need a good system. So that you can get to know someone and just like I was able to get to know my boyfriend better and in the best way was that I only needed to resort to hacking Instagram without programs and achieve it like the professionals the best of all and that I have not yet mentioned is that the whole procedure is really a matter of minutes so that you find yourself doing what you require and in the best way the process will be totally simple and before you know it you will find yourself knowing everything that you wanted to know about someone else.
I had to[ hack Facebook ](https://hackfreeonline.com/facebook/
)easily to find out what I needed to know what my best friend was hiding from me because for a long time I have realized that his behavior is different and that really worries me because if he doesn't tell me what he has then I don't know how to help him but honestly as I know him I know that it won't be easy to reach him because when he locks himself up it is the most complicated thing hacking Instagram because I set out to investigate to the bottom of the situation what was happening to be able to from this get what I need, that's how I found out about this page because it had previously been recommended to me.
