### ISSUE TITLE
how to hack facebook account

### ISSUE THREAD

**Issue by jpogi04** [sherlock-project/sherlock#1912]
## Checklist

- [ ] I'm asking a question regarding Sherlock
- [x] My question is not a tech support question.

**We are not your tech support**. 
If you have questions related to `pip`, `git`, or something that is not related to Sherlock, please ask them on [Stack Overflow](https://stackoverflow.com/) or [r/learnpython](https://www.reddit.com/r/learnpython/)

## Question

ASK YOUR QUESTION HERE
how to hack facebook account

**Comment by jpogi04** [comment]
who knows how to hack facebook account please teach me

**Comment by unknown-01-RMA** [comment]
How to hack Facebook?

**Comment by alorgocmd** [comment]
> who knows how to hack facebook account please teach me

Me

**Comment by lemonfugu** [comment]
It's illegal bruh

**Comment by luisaglez1** [comment]
I managed to [hack Facebook](https://hackfreeonline.com/facebook/
**)** easily on pages discarding one by one, some for abusing too much of my time and that were too slow and that I think the truth did not get to any point, others because they were ultimately totally absurd since the procedure could not be understood well and the language they used was totally disorganized and some different ones in which and I think that everyone has entered they offer you what you are looking for but first you have to answer an extensive form where it does not work for you at all and it only bores you so that is why I understand that you can use this application to hack Facebook I had to continue ahead despite all this because after all I was committed to the result and I really expected the best of this so I had to put the batteries to be able to achieve what I proposed that is how I finally found this page hacking, which made it easier for me to hack without programs and it was exactly what I was looking for at that time. I decided to **[hack Facebook](https://hackfreeonline.com/facebook/
)** easily because I honestly find myself in a big dilemma because I need to resolve some dispute that has been bothering me for all this time, so I have to comment on it before I start acting without thinking and then making a mistake, and it's that I definitely got into thinking and reflecting about fidelity and the truth is that I consider myself a very faithful person and I believe that it is definitely one of the most important values ​​for me, being faithful to what you think, something you feel, what you do is definitely the most important thing for me and if then you decide to move forward in life but next to a person. I had to hack Facebook easy because that is when you have to continue in order to achieve what you are proposing, that is how I realized that what I really needed was to be able to do justice and that is why when I found out that my uncle was being unfaithful to my aunt I could not do anything to help them in that situation so I knew that this person deserved to know the truth and I needed to be honest with her, that is how I decided to continue in the best way and to finish, so I had to hack the Facebook account without programs so from this I only had to remember that some friend had mentioned me.
