### ISSUE TITLE
Python cant find __main__ module

### ISSUE THREAD

**Issue by An020** [sherlock-project/sherlock#1936]
## Checklist

- [x ] I'm reporting a bug in Sherlock's functionality
- [x ] The bug I'm reporting is not a false positive or a false negative
- [x ] I've verified that I'm running the latest version of Sherlock
- [x ] I've checked for similar bug reports including closed ones
- [x ] I've checked for pull requests that attempt to fix this bug

## Description

WRITE DESCRIPTION HERE
Verison of sherlock: i dont know because it showed cant find __main__ module instead of the verison

https://imgur.com/a/pzRzIvx 
( the image of me checking the verison) (i installed all the requirements in the .txt file provided) 
( this error also appear when i use other command of the program)

**Comment by Feastsandfires** [comment]
Experienced also error. Works when run from file directly in directory, cd to folder and run _main_.py.

**Comment by matheusfelipeog** [comment]
Thank you for opening this issue, @An020.

Currently, to run the project, you must be in the context of the locally cloned repository. In the screenshot you provided, you are in `*\Desktop\` instead of `*\Desktop\sherlock\`.

After cloning the repository, make sure to change to the directory using the command:

```bash
cd sherlock
```
