### ISSUE TITLE
Dependencies pandas and numpy don't install with pip on Termux

### ISSUE THREAD

**Issue by kbarrett975** [sherlock-project/sherlock#1945]
![Screenshot_20231124_151500_Termux](https://github.com/sherlock-project/sherlock/assets/67570884/eef209a6-844b-4912-a049-d031f900a9ea)

## Checklist

- [ ] I'm reporting a bug in Sherlock's functionality
- [ ] The bug I'm reporting is not a false positive or a false negative
- [ ] I've verified that I'm running the latest version of Sherlock
- [ ] I've checked for similar bug reports including closed ones
- [ ] I've checked for pull requests that attempt to fix this bug

## Description

WRITE DESCRIPTION HERE

**Comment by kbarrett975** [comment]
What am I missing

**Comment by Kamski18** [comment]
I get the same problem.. I already install libcrypt and update all package to the newest version but after i ran

 _pip3 install -r requirements.txt_  

It still show the same error..may i know why

![Uploading Screenshot_2023-12-11-13-44-49-17.jpg…]()

**Comment by Kamski18** [comment]
![Screenshot_2023-12-11-13-44-49-17](https://github.com/sherlock-project/sherlock/assets/151996410/3c25f083-d717-4653-acf4-7371c0359de6)

**Comment by matheusfelipeog** [comment]
Thank you for providing the complete installation log, @Kamski18.

Try updating your `pip`, `setuptools`, and `wheel` with the following command:

```bash
python3 -m pip install --upgrade pip setuptools wheel
```

After that, try installing the dependencies again:

```bash
pip3 install -r requirements.txt
```

**Comment by Kamski18** [comment]
I already update using the following command but still get an error

![Screenshot_2023-12-11-16-39-02-48](https://github.com/sherlock-project/sherlock/assets/151996410/f4a43238-6dfb-481c-9ec8-b44ad3f70464)

**Comment by matheusfelipeog** [comment]
@kbarrett975 @Kamski18 It seems that Termux has issues building the `numpy` package wheel locally. The `pandas` package depends on `numpy`, so this error is generated when the build fails.

I've noticed that this is a common problem in Termux, with several complaints on:

link 1: https://github.com/termux/termux-packages/issues/10808
link 2: https://github.com/termux/termux-app/issues/3048
link 3: https://stackoverflow.com/questions/77228553/error-cant-install-pandas-library-on-termux-2023
link 4: https://github.com/termux/termux-app/issues/3225

Unfortunately, to use the sherlock project in a Termux environment, you'll have to follow a few extra steps for now.

First, update the package list and install updates:

```bash
pkg update && pkg upgrade
```

Provide the `y` option for all when prompted.

The Termux community provides a repository of pre-built Python packages, called `tur` (Termux User Repository). This will avoid having to build some packages locally.

Let's install `tur-repo` and `build-essential`, which contains some necessary packages for building other packages:

```bash
pkg install build-essential tur-repo
```

After that, force an update on the package list again:

```bash
pkg update
```

Now, let's install the pre-built `pandas` and `numpy` packages globally:

```bash
pkg install python-pandas python-numpy
```

This will install the packages. You can check using:

```bash
pip list
```

Now you are ready to install the sherlock project dependencies:

```bash
pip install -r requirements.txt
```

---

I personally recommend installing sherlock project dependencies in a virtual environment instead of globally to avoid conflicts with dependencies from other projects.

To create a virtual environment within the locally cloned sherlock project repository, use the following command:

```bash
python -m venv --system-site-packages venv
```

The `--system-site-packages` flag will copy the packages installed globally to the virtual environment in `venv`. This ensures that we have `pandas` and `numpy` within the virtual environment.

To activate the virtual environment, use the following command:

```bash
source venv/bin/activate
```

Now, you can install the sherlock project dependencies in this virtual environment:

```bash
pip install -r requirements.txt
```

When you finish using sherlock, don't forget to deactivate the virtual environment:

```bash
deactivate
```

---

I've tested this, and it worked perfectly. I hope it works for you too. If you encounter any other problems, please let me know.

**Refs:**

ref 1: https://wiki.termux.com/wiki/Python
ref 2: https://github.com/termux-user-repository/tur
ref 3: https://docs.python.org/3/library/venv.html

**Comment by Kamski18** [comment]
Did anyone know how to solve the problem above?

**Comment by Kamski18** [comment]
THANKS! It work finally..Thank you for providing help for me!

**Comment by Mitchellallan37** [comment]
Worked for me Ty Vm!

**Comment by sheneeb** [comment]
This doesn't work on Facebook prophet same pandas error

**Comment by vFeruz** [comment]
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
