### ISSUE TITLE
Some sites always appear with the username I entered even though it doesn't exist

### ISSUE THREAD

**Issue by R1ckE01** [sherlock-project/sherlock#1999]
sites like: RocketTube,  CGTrader,  xHamster, Fiverr,  Modelhub. are always repeated in all the usernames I enter

**Comment by EarthRockerBam** [comment]
Yep. Also xhamster and heavy-r for NSFW. This tool doesn't seem to work at all for me. It doesn't even find things I can find on google or the biggest social media platforms.

**Comment by roflmaostc** [comment]
Same for me
```
╰─➤  python sherlock ajdlsajdlksajdjqeadslajskhdslaskjdlajsdjasjdj                                                                      [19-02-24 | 10:49:33]
[*] Checking username ajdlsajdlksajdjqeadslajskhdslaskjdlajsdjasjdj on:

[+] CGTrader: https://www.cgtrader.com/ajdlsajdlksajdjqeadslajskhdslaskjdlajsdjasjdj

[*] Search completed with 1 results
```

**Comment by Vilagamer999** [comment]
`sherlock % python3 sherlock qkqdhqiudhqwiuhdiuqhw --nsfw
[*] Checking username qkqdhqiudhqwiuhdiuqhw on:

[+] 8tracks: https://8tracks.com/qkqdhqiudhqwiuhdiuqhw
[+] APClips: https://apclips.com/qkqdhqiudhqwiuhdiuqhw
[+] CGTrader: https://www.cgtrader.com/qkqdhqiudhqwiuhdiuqhw
[+] Heavy-R: https://www.heavy-r.com/user/qkqdhqiudhqwiuhdiuqhw
[+] Modelhub: https://www.modelhub.com/qkqdhqiudhqwiuhdiuqhw/videos
[+] Motherless: https://motherless.com/m/qkqdhqiudhqwiuhdiuqhw
[+] NitroType: https://www.nitrotype.com/racer/qkqdhqiudhqwiuhdiuqhw

[*] Search completed with 7 results`

lol

**Comment by eliminmax** [comment]
I have 2 usernames that I use on different sites, and the following websites came up for both of them (in NSFW mode). I have never created accounts on them, and as far as I know, I'm the only one to ever use either username.

* `https://hackerearth.com/@{user}`
* `https://motherless.com/m/{user}`
* `https://music.yandex/users/{user}/playlists`
* `https://www.baby.ru/u/{user}/`
* `https://www.cgtrader.com/{user}`
* `https://www.g2g.com/{user}`
* `https://www.metacritic.com/user/{user}`
* `https://www.modelhub.com/{user}/videos`
* `https://xhamster.com/users/{user}`

Informally testing some of those:

hackerEarth currently redirects all URLs to a page stating that it's down for maintenance until 02:30 UTC on February 21, 2024, so that issue is likely temporary.

YandexMusic, in a Firefox private window, after a CAPTCHA, displayed a 404 page for one of them, but for `curl --fail` on the same exact URL, returns an empty output with no error code.

G2G redirects to the homepage for both of my usernames, but displays the user page for the test username from `data.json`.

CGTrader redirets to `https://www.cgtrader.com/not_found` for both of my usernames, but redirects to the user page for the test username from `data.json`

Metacritic does not display the "User not found" string when accessed using curl, and in a Firefox private window, it displays a message simply stating that "`This user hasn’t rated anything yet`".

BabyRU displays an error page reading `Доступ с вашего IP-адреса временно ограничен`, which, according to Google Translate, translates to "Access from your IP address is temporarily limited". I don't know if that's because I was messing with this tool or because my IP address is from the USA.

**Comment by ChuckBaby81** [comment]
This found 1 site for me that was a legitimate find, other than that...most were garbage and not useful or helpful.

**Comment by ppfeister** [comment]
@ChuckBaby81 Talking about Sherlock in general or the linked one?

**Comment by bert0ccidev** [comment]
hacker simulator lol
