### ISSUE TITLE
# clone the repo $ git clone https://github.com/sherlock-project/sherlock.git  # change the working directory to sherlock $ cd sherlock  # install the requirements $ python3 -m pip install -r requirements.txt

### ISSUE THREAD

**Issue by d1feqt** [sherlock-project/sherlock#2060]

**Comment by Aminser99** [comment]
i got this message after i try to install requirements
 Defaulting to user installation because normal site-packages is not writeable
WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping

**Comment by ppfeister** [comment]
That file does not exist and that is not a supported method. [Read the install options here](https://github.com/sherlock-project/sherlock?tab=readme-ov-file#installation).
