### ISSUE TITLE
Yandex Music has a captcha

### ISSUE THREAD

**Issue by 00-kat** [sherlock-project/sherlock#2071]
## Checklist

- [x] I'm reporting a website that is returning **false positive** results
- [x] I've checked for similar site support requests including closed ones
- [x] I've checked for pull requests attempting to fix this false positive
- [x] I'm only reporting **one** site (create a separate issue for each site)

## Description

Here's a random username that can't possibly exist: [ecfhlmiuewfimcuhem](https://music.yandex/users/ecfhlmiuewfimcuhem/playlists).

Here's the username from [data.json](https://github.com/sherlock-project/sherlock/blob/master/sherlock/resources/data.json#L2214): [ya.playlist](https://music.yandex/users/ya.playlist/playlists)

When I visit either, I get a captcha (note: JS is disabled in my browser):
![image](https://github.com/sherlock-project/sherlock/assets/65649991/3c93012d-991a-46a2-b0af-60edf5772eec)

Unless Sherlock uses Selenium/Pyppeteer, which i highly doubt (it's not in requirements.txt), this captcha isn't really avoidable (I think). Maybe it even shows up with JS enabled, which I didn't check.

I'm not opening a PR removing YandexMusic because it could be an issue that only happens for me, or maybe it's possible to bypass this captcha.

**Comment by ppfeister** [comment]
@cd-CreepArghhh Can you share the raw html used for that page? I'll likely be able to add it to #2068

**Comment by cd-CreepArghhh** [comment]
Huh, interestingly there's no captcha now but there's a 404 page and a profile. Maybe I'll run Sherlock a couple times then try again.

**Comment by ppfeister** [comment]
If you do end up hitting it again drop a ping

Testing yandex in a PITA on my end having to use vpns and such, and even when I do, it apparently trusts me _implicitly_ and refuses to rate limit or captcha me

**Comment by ppfeister** [comment]
(if the captcha page returns a status code _other than 200_, we can also use that as a simpler resolution)

**Comment by cd-CreepArghhh** [comment]
Okay, found out that spamming them with requests gets you a captcha fast. Running Sherlock 4 times resulted in one captcha, and my browser got 2 in 6 requests.

You're going to have to run the HTML through some prettifier though (I don't know any) since it's all on one line.

Note: Github won't let me upload .html files, so rename the .txt to a .html, thanks.

[Oops, Captcha!.txt](https://github.com/sherlock-project/sherlock/files/14921158/Oops.Captcha.txt)
[Oops, Captcha!_files.zip](https://github.com/sherlock-project/sherlock/files/14921159/Oops.Captcha._files.zip)

I'll spam a few requests with python now to check the status code.

**Comment by cd-CreepArghhh** [comment]
Finished. Out of 100 requests, the first request was a 404 (i.e. no captcha) then the rest were all 200s (thus captcha). Status code isn't going to be of any use.

**Comment by ppfeister** [comment]
Gonna push a hopeful fix. If you want to be added as a co-author you can drop your github no-reply email/other github email here and a name. Or link to somewhere that has it.

Otherwise I'll push as a single committer.

**Comment by cd-CreepArghhh** [comment]
Just push as single committer

**Comment by ppfeister** [comment]
Done. Seems to have not broken anything on my end -- can you pull and validate all 3 cases as well

(captcha, valid, not valid)

**Comment by ppfeister** [comment]
Just realized I forgot a case --- not valid in country. Will add that now. Shouldn't make a difference for the captcha tests.

**Comment by cd-CreepArghhh** [comment]
I don't think it worked, since there's still a false-positive. By the way, I'm pretty sure I'm still in the blacklist or whatever Yandex Music has going on, so it will be a while before I can test the other two cases.
```
$ git clone https://github.com/ppfeister/sherlock.git  # hope I cloned the right repo...
$ cd sherlock
$ python sherlock ecfhlmiuewfimcuhem --site YandexMusic
[*] Checking username ecfhlmiuewfimcuhem on:
[+] YandexMusic: https://music.yandex/users/ecfhlmiuewfimcuhem/playlists

[*] Search completed with 1 results
```

**Comment by ppfeister** [comment]
hm......... lemme re eval and get back

**Comment by ppfeister** [comment]
@cd-CreepArghhh Just got back

Noticed that you didn't run with the `--local` flag. When you don't use this flag, it pulls from the repo by default instead of our local patched data.json. Can you test one more time but while using that flag? _(this won't be necessary if the patch gets merged upstream)_

When using that flag on my end, it seems to give the expected result for each of the four cases (not valid, valid, captcha, geoblock).

_(that flag messes with me quite a bit.....)_

**Comment by cd-CreepArghhh** [comment]
Yay, it works! `ecfhlmiuewfimcuhem` doesn't show up, `ya.playlist` does, and I didn't get any false positives even after spamming the command 30+ times. I didn't realise that it grabbed a `data.json` from GitHub instead of the local one by default (probably so you don't need to `git pull` as often).

Also, I'm not sure what the geoblock case is so I can't really test that. (I assume I could try running it through a bunch of tor nodes until I hit it, but I don't have time for that right now).

**Comment by ppfeister** [comment]
I get geoblocked here in the states, so it was an easy test for me to run, lol

I'll go ahead and link your Issue to that PR so it gets closed when and if it (hopefully) gets merged
