### ISSUE TITLE
Tinder False Positive

### ISSUE THREAD

**Issue by aaeissa** [sherlock-project/sherlock#211]
Sherlock found a Tinder profile for a username I queried, but going to the URL shows the "Looking for Someone?" error message. 

I saw that error message hardcoded in data.json: 

```
  "Tinder": {
    "errorMsg": "Looking for Someone?",
    "errorType": "message",
    "rank": 1730,
    "url": "https://www.gotinder.com/@{}",
    "urlMain": "https://tinder.com/",
    "username_claimed": "blue",
    "username_unclaimed": "noonewouldeverusethis7"
  }
``` 

So it seems like it should have been caught?

**Comment by hoadlck** [comment]
Hmm.... Sounds like the classic false positive (which Sherlock always has problems with when it uses the Error Message detection method).  Usually, it is because the site changed their error text.

But, in this case I am not seeing any problem: the tests pass for this site.

Is the problem repeatable? What is the username that you queried against?

**Comment by sdushantha** [comment]
@hoadlck I think we should make a template for issues. If they are reporting a false positive, they have to provide the username they used. 

This will make it easier for us to fix the issue.

**Comment by aaeissa** [comment]
@hoadlck @sdushantha sorry for the delay. I was not able to reproduce the error, actually. I ran the script (no other options except a single username) and got the false positive one time, and did not get that result the next time.

I realize this hinders troubleshooting, but unfortunately I wouldn't feel comfortable providing the username in a public forum like this since I was performing an investigation of sorts. I suspect many others users would share that hesitation if asked to provide it as well, given the nature of the Sherlock tool. I do think a template for issues/false positives would help, but I'm not sure how successful requiring the username would be. Just wanted to share my thoughts.

**Comment by sdushantha** [comment]
@aaeissa 
No worries, we all have other stuff in our lives other than replying to GitHub issues :)

> I realize this hinders troubleshooting, but unfortunately I wouldn't feel comfortable providing the username in a public forum like this since I was performing an investigation of sorts.

Yeah, that is very understandable.

> I do think a template for issues/false positives would help, but I'm not sure how successful requiring the username would be.

True, maybe we could have a tick box asking if they tested other usernames and got the false positive.
Because like you mentioned above, this false positive only happened once.

**Comment by hoadlck** [comment]
Looks like this issue can be closed now.  These intermittents are a pain.
