### ISSUE TITLE
archive.org returning 200 response for any query

### ISSUE THREAD

**Issue by Noam-Alum** [sherlock-project/sherlock#2137]
### Site name

archive.org

### archive.org is returning 200 response for any query:
![image](https://github.com/sherlock-project/sherlock/assets/132448828/2bef2fda-9732-481d-8028-7e414a9ad3a5)
![image](https://github.com/sherlock-project/sherlock/assets/132448828/8d0eb297-79c7-4b39-a775-a7a4e004b340)
![image](https://github.com/sherlock-project/sherlock/assets/132448828/3f5bcdfb-dee1-4f10-944a-71d51411f65f)

### I'm guessing this is the only way you check the availability
![image](https://github.com/sherlock-project/sherlock/assets/132448828/9e74d439-6d62-407c-8668-848107318b59)

**Comment by ppfeister** [comment]
Archive[.]org uses message data to check availability as in L163-170 of the manifest [[here]](https://github.com/sherlock-project/sherlock/blob/1cd81385b21833b4f849667c32a86609337fd73c/sherlock/resources/data.json#L163). Status code is ignored for this target.

_Aside: Your screenshot focuses on the `response_url` errorType test, but what you actually want is the `message` errorType test found on L401-425 of the runner [[here]](https://github.com/sherlock-project/sherlock/blob/1cd81385b21833b4f849667c32a86609337fd73c/sherlock/sherlock.py#L401)._

The query url is also `https://archive.org/details/@{}?noscript=true` rather than `https://archive.org/details/@{}`.

Is does seem that Archive[.]org has changed their error message, however, which looks like the cause of your F+, and I was able to reproduce.

Would you like to open a PR? Should be a simple change in the manifest to that new errorMsg.

**Comment by ppfeister** [comment]
By the way, the screenshots are greatly appreciated. Shows _exactly_ how to reproduce.

**Comment by Noam-Alum** [comment]
I'm not sure, should it be some thing like this?

```
  "Archive.org": {
    "errorMsg": "The resource could not be found.",
    "errorType": "status_code",
    "url": "https://archive.org/details/@{}",
    "urlMain": "https://archive.org",
    "urlProbe": "https://archive.org/details/@{}?noscript=true",
    "username_claimed": "blue"
  },
  ```
  
 This is the current  page results:
  ```html
<body data-new-gr-c-s-check-loaded="14.1174.0" data-gr-ext-installed=""><h1>404 Not Found</h1>
The resource could not be found.

</body>
```

And this is the status code it gets;
![image](https://github.com/sherlock-project/sherlock/assets/132448828/a9b368a0-fbe6-4bf1-b387-9b201e6d97d9)

**Comment by ppfeister** [comment]
Well.... that's not the response I was expecting.
After some further digging, it seems that the Archive is under attack, causing some versions to fail (i.e. the noscript version).

Seems they posted to Twitter about a DDoS attack several times over the last few days.

I say we ride this one out and see. Knowing this, there's a good chance it'll return to normal operation pretty soon. I've added a test condition for Archive downtime, to suppress this type of F+.
