### ISSUE TITLE
Latest pull 0.14.4 exits with error.

### ISSUE THREAD

**Issue by radiophonic** [sherlock-project/sherlock#2168]
### Installation method

Built from source

### Description

I normally run this from source and it's been working for well over a year now. However the latest pull exits with the following error:

```
Traceback (most recent call last):
  File "/home/sint/Tools/osint/sherlock/sherlock/sherlock.py", line 28, in <module>
    from .__init__ import ( # noqa: E402
ImportError: attempted relative import with no known parent package
```

Any suggestions would be great, thanks.

### Steps to reproduce

start using python: python3 sherlock.py someusername

### Additional information

Linux Mint 21.3, Python 3.10.12

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ppfeister** [comment]
Sherlock is moving towards being a proper installable and importable package rather than just a standalone script.

This allows for `pip install sherlock-project` from PyPI or `pip install .` from source, before simply `sherlock {...}` from anywhere. Normally, you're also able to run `python3 -m sherlock {...}` to run straight from source, but I'll have to validate that later to make sure that the relative imports are correct.
