### ISSUE TITLE
running issues

### ISSUE THREAD

**Issue by manishyadav1400** [sherlock-project/sherlock#219]
hi i am having issues while running ,how to resolve this please help
`usage: sherlock.py [-h] [--version] [--verbose] [--rank]
                   [--folderoutput FOLDEROUTPUT] [--output OUTPUT] [--tor]
                   [--unique-tor] [--csv] [--site SITE_NAME]
                   [--proxy PROXY_URL] [--json JSON_FILE]
                   [--proxy_list PROXY_LIST] [--check_proxies CHECK_PROXY]
                   [--print-found]
                   USERNAMES [USERNAMES ...]
sherlock.py: error: the following arguments are required: USERNAMES
`

**Comment by manishyadav1400** [comment]
![Screenshot (16)](https://user-images.githubusercontent.com/46298091/60981637-57f89500-a354-11e9-9062-3bf6f03a9179.png)

**Comment by tommywei110** [comment]
`python3 sherlock.py user123`
You would run a query like this. Gotta put in the username you're looking for

**Comment by hoadlck** [comment]
Sherlock is a command line program. Since PyCharm is an IDE, you have to tell it what command line options you want to use. The message you are giving is because you are running Sherlock without giving it any users to search for.

Here is a [StackOverflow](https://stackoverflow.com/questions/31884252/how-to-run-python-programs-in-pycharm-with-passing-parameters) entry talking about how to add command line options.  I don't use PyCharm, so I am not sure if this works for your specific version.  But, this is what is happening.

**Comment by LeeHarvey** [comment]
![Clipboard02](https://user-images.githubusercontent.com/51308286/61032340-99e11400-a404-11e9-89f2-3714112b734e.jpg)

**Comment by monraPH** [comment]
> `python3 sherlock.py user123`
> You would run a query like this. Gotta put in the username you're looking for

I've try this kind of format but it doesn't work and then I got error message 
![dddf](https://user-images.githubusercontent.com/44535940/61172900-0e12e780-a5be-11e9-8d10-860756cbe4d6.JPG)

**Comment by sdushantha** [comment]
@monraPH 
Before you run Sherlock, you have to install the all the modules that are required by running this:
```bash
$ cd sherlock
$ pip3 install -r requirements.txt
```

**Comment by hoadlck** [comment]
This issue appears to be an environmental issue rather than a problem with Sherlock itself.  It also has been hanging out for some time.  So, I am closing it out now to remove the clutter.
