### ISSUE TITLE
How to import requests_futures

### ISSUE THREAD

**Issue by cont3nted** [sherlock-project/sherlock#224]
![sherlock](https://user-images.githubusercontent.com/50903697/61061878-ae86d180-a42f-11e9-983c-e77f3b28c58f.JPG)

Not sure why it does not have this module

**Comment by bbaydar90** [comment]
I had the same issue on my Raspberry Pi 3 running Raspbian. Solution: Check if requests-futures is installed under /usr/lib/python3/dist-packages. If no you need to manually install it. If yes it means that this folder is not on your path and that's why python can't find the module. Add it manually by entering the file (nano sherlock.py) and add: sys.path.append('/usr/lib/python3/dist-packages')

**Comment by vuduclyunitn** [comment]
Can you try: pip install requests-futures?

**Comment by cont3nted** [comment]
Thanks for your help guys, but it's still not working

**Comment by sdushantha** [comment]
@cont3nted Have you tried installing all the packages from the `requirements.txt`?
Just run this:
```bash
pip install requirements.txt
```

**Comment by cont3nted** [comment]
I tried that already, it worked on ubuntu but it does not work on Kali

**Comment by sdushantha** [comment]
@cont3nted Could you please show me the output of:
```bash
pip3 --version
```

**Comment by TheVGAMER** [comment]
pip 19.0.3

**Comment by hoadlck** [comment]
This issue appears to be an environmental issue rather than a problem with Sherlock itself.  It also has been hanging out for some time.  So, I am closing it out now to remove the clutter.
