### ISSUE TITLE
Requesting support for: Adding https://www.exophase.com

### ISSUE THREAD

**Issue by kevin-fagan** [sherlock-project/sherlock#2248]
### Site URL

https://www.exophase.com

### Additional info

A  username can be found like such: https://www.exophase.com/user/USERNAME/. Exophase will return a 404 if the user is not found. I am happy to add it myself, not sure the what process this repo follows for making changes :) 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ppfeister** [comment]
Hey @kevin-fagan! There's not much of a process to follow, really. Well, nothing project specific --- you'll have to know how to use git and github of course

If you'd like to add it yourself, you can just add an entry to the data.json file in sherlock_project/resources/, mirroring the format of any other entry that uses status_code. When cloned, you can use `poetry install` and then `poetry run sherlock --site exophase --local user123` to test changes. Just prefacing the command with [poetry run](https://python-poetry.org/docs/#installation) to use the venv and sherlock flag --local to use the local data.json you're editing rather than the remote one here on github.

Let me know if you need anything
