### ISSUE TITLE
cant clone the sherlock

### ISSUE THREAD

**Issue by LoneCrise** [sherlock-project/sherlock#2253]
### Installation method

Kali repository (via apt)

### Description

i  cant clone the repostiory its showing the error.
LIKE BELOW:-
git clone https://github.com/sherlock-project/sherlock.git
cd sherlock
Cloning into 'sherlock'...
fatal: unable to access 'https://github.com/sherlock-project/sherlock.git/': Could not resolve host: github.com
cd: no such file or directory: sherlock

### Steps to reproduce

i have use all the steps in youtube video but i can get the clone access please help me to find out why this error comes .

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ppfeister** [comment]
I take it you're actually building from source, rather than using apt as selected. Also, the error message you are being presented is caused by something in your local environment and not something we can readily diagnose here.

Reference the readme on the first page for up to date instructions. The YouTube video is outdated (and the new method is easier anyways).

Report back with how it goes and if you need any help with the options listed
