### ISSUE TITLE
ERROR: Bad Response 

### ISSUE THREAD

**Issue by Cyph3rByte** [sherlock-project/sherlock#2280]
### Installation method

Other (indicate below)

### Description

Installation method:
via blackarch

when running 'sherlock <username>' I get the following error output:
"A problem occurred while checking for an update: list index out of range
ERROR:  Bad response while accessing data file URL 'https://raw.githubusercontent.com/sherlock-project/sherlock/master/sherlock/resources/data.json'."

### Steps to reproduce

$sherlock jeff.h
>A problem occurred while checking for an update: list index out of range
>ERROR:  Bad response while accessing data file URL 'https://raw.githubusercontent.com/sherlock-project/sherlock/master/sherlock/resources/data.json

### Additional information

I created a VM with Debian and installed it using pip, then using Docker and it worked without problems. I believe the defect is in the package contained in the Black Arch repository.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ppfeister** [comment]
So, BlackArch is weird. It's the only distro that's still using some esoteric versioning scheme rather than semver, despite many months having passed since Sherlock's adoption of (sorta-)semver. That being said, the BlackArch repo is currently showing version `2460.9e111a3` for 9e111a3 (as of four days ago), so it doesn't seem far behind, despite being _odd_.

That error message is certainly something you'd see from a 0.14.3 build, though (or _maybe_ 0.14.4).

I have to ask just to be thorough -- are you sure you're up to date?

There are several things wrong with the BlackArch [PKGBUILD](https://github.com/BlackArch/blackarch/blob/master/packages/sherlock/PKGBUILD), but I'm not sure if they would cause issues with distrib. And if they do, I'm not sure where the old version is coming from, considering it's no longer available on the pkgbuild repo.

**Comment by fuze2333** [comment]
I also encountered this issue and haven't resolved it yet.

**Comment by Cyph3rByte** [comment]
Thanks for your attention, and sorry for the silly mistake.
