### ISSUE TITLE
Shipping broken. https://raw.githubusercontent.com/sherlock-project/sherlock/master/sherlock/resources/data.json not found

### ISSUE THREAD

**Issue by s1nistr4** [sherlock-project/sherlock#2282]
### Installation method

PyPI (via pip)

### Description

When running sherlock, it gives an error saying https://raw.githubusercontent.com/sherlock-project/sherlock/master/sherlock/resources/data.json is not found, which is true. 

### Steps to reproduce

Run sherlock with any username

### Additional information

This issue seems to have happened because a file in the github repo was moved. It would be nice for it to just download the file and use it as a template locally, rather than using github for it. It would completely prevent issues like this in the future.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ppfeister** [comment]
When did you install and what does `sherlock --version` output?

**Comment by scottnzuk** [comment]
> When did you install and what does `sherlock --version` output?

sherlock 0.14.4
Python HTTP for Humans.:  2.32.2
Python:  3.12.5
(base) -Pro sherlock %

**Comment by ppfeister** [comment]
We've been shipping 0.15.0 since July 8 [(ref)](https://pypi.org/project/sherlock-project/#history). You just need to update Sherlock to the most recent version.

Also, worth noting --

> It would be nice for it to just download the file and use it as a template locally, rather than using github for it.

This method would result in wildly inaccurate results as websites change way too frequently. By pulling the latest manifest from a remote source, it's able to at least _reduce_ false positives and negatives. That being said, `--local` is still available which _will_ use a local (but very rapidly outdated) copy as a backup.
