### ISSUE TITLE
sherlock as a python library

### ISSUE THREAD

**Issue by peterclemenko** [sherlock-project/sherlock#2293]
### Description

being able to use sherlock as a library in python scripts would be helpful for automation flows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ppfeister** [comment]
Already doable!

I've done the same as a dependency of [Sylva](https://github.com/ppfeister/sylva) (ongoing). You can see how it was implemented [here](https://github.com/ppfeister/sylva/blob/master/src/sylva/modules/sherlock.py).

I have plans to clean up the imports a bit, so that you can do `from sherlock_project ...` rather than `from sherlock_project.sherlock ...`, but that's down the line. Type defs are mostly there if you use static type validation, with #2277 (soon, need to push a change) set to add \~proper\~ support for type checks with things like mypy.

Proper documentation for use as a dependency will probably be added at some point.
