### ISSUE TITLE
GitLab check method

### ISSUE THREAD

**Issue by tdh8316** [sherlock-project/sherlock#232]
Currently, Sherlock supposes GitLab's error type is a message.
But I think there is a more efficient way. that's precisely response URL.

For example, user tdh8316 does not exist on GitLab and when I enter the address `https://gitlab.com/tdh8316`, it redirects to `https://gitlab.com/users/sign_in`

Therefore I'd like to recommend replacing message, which is GitLab's error type with response_url.

**Comment by hoadlck** [comment]
What you are talking about is the Response URL detection method.  It is documented in the [Adding Sites To Sherlock](https://github.com/sherlock-project/sherlock/wiki/Adding-Sites-To-Sherlock) guide.

As I get time, I do convert sites away from the error message detection method.

**Comment by satznova** [comment]
Hi, I have raised a PR #245 for the enhancement of this issue.

I have preferred Gitlab API for this issue because I faced a problem while working on this.

My Gitlab username is: satznova

If I try https://gitlab.com/users/Satznova , I got below response:
**HTTP status code:** 302
**Response Text:** 
<html><body>You are being <a href="https://gitlab.com/satznova">redirected</a>.</body></html>

The Gitlab usernames are unique and not case sensitive but still, the redirection occurs to correct case that was created within the first place (I created the username with small case 's')

This is a known issue and using the API for checking for the username solves our problem.
Ref: https://gitlab.com/gitlab-org/gitlab-ce/issues/38304

**Comment by tdh8316** [comment]
Closed according to (#245)
