### ISSUE TITLE
python3 sherlock.py user123 doesnot output any result

### ISSUE THREAD

**Issue by DarkRaider29** [sherlock-project/sherlock#269]
![Capture](https://user-images.githubusercontent.com/52749660/61455370-fc3d9580-a96b-11e9-8c68-42087ad5719f.PNG)

i have done the installation right but i cant get it working

**Comment by sdushantha** [comment]
Hmm... that is very strange because I just tried it and it works. Might something to do with Windows.
@hoadlck, I think you use Windows, do you want to take a look at this?

**Comment by tdh8316** [comment]
I'm using Windows 10, but Sherlock works for me.
![2019-07-19-08-53-54](https://user-images.githubusercontent.com/20598077/61499584-c5668e80-aa02-11e9-8fae-ef08211e2044.png)

I ran Sherlock with this command:
```cmd
> git clone https://github.com/sherlock-project/sherlock.git
> cd sherlock
> python sherlock.py user123
```

**Comment by hoadlck** [comment]
The problem is with the Python install itself.  Using ```python3``` does not work on Windows (unless someone went thru the effort to specifically setup an alias like that).

You need to figure out your install first.  If you know where your Python is installed, you can type in the absolute path to it as well.  The ```where``` command will tell you where a program is installed (assuming that it is located on the PATH).  You should check the Python version before getting too far into running Sherlock itself.

In windows, here are some commands that can be useful to see what is gong on:
```
C:\Users\hoadlck>where python
C:\python36\python.exe

C:\Users\hoadlck>where python3
INFO: Could not find files for the given pattern(s).

C:\Users\hoadlck>python --version
Python 3.6.5
```
Try running the above command on your setup.

**Comment by hoadlck** [comment]
This issue appears to be an environmental issue rather than a problem with Sherlock itself.  It also has been hanging out for some time.  So, I am closing it out now to remove the clutter.

**Comment by ergashevzuhriddin579-eng** [comment]
@scott_em1ly

**Comment by ergashevzuhriddin579-eng** [comment]
@scott_em1ly
