### ISSUE TITLE
Massive Issues

### ISSUE THREAD

**Issue by ghost** [sherlock-project/sherlock#308]
Getting Errors Connecting to :
 Aptoide, Basecamp, Carbonmade, ColourLovers, Crevado, Itch.Io, Jimdo, Rajce.net, Webnode, Wix. As of today it is also crashing and causing complete system freezes on both systems I am utilizing it on, 1 is a Virtual Box Kali Linux 2.0 the other is a dedicated Kali Linux 2.0 system . 

Another common problem is if you use say "First.Lastname" it will get results for say www.com/independent.academia.edu/FIRSTNAME instead of www.com/independent.academia.edu/FIRSTNAME.LASTNAME 

this is on quite a few of the search as well. 

I have also observed that when you run FirstName.LastName say
Python3 sherlock.py firstname.lastname -r it produces "Illegal Username Format" 

another issue is i'll go to run sherlock and it returns only 3 results and ends. 

Distributor ID:	Kali
Description:	Kali GNU/Linux Rolling
Release:	2019.3
Codename:	kali-rolling

using latest version of sherlock

**Comment by hoadlck** [comment]
It does sounds like there is some issue with your environment.  Some sites do not respond if they don't like the IP address that you are coming from.

The error message with the "Illegal Username Format" is because some sites do not accept usernames with a "." in them.  If Sherlock said that there was no username like that (which would be true), it would still be misleading: no one could have a username with a "." at that site.

Unfortunately, we do not have the checking for the valid username format for all sites.  So, some messages reporting available usernames may not be actually true.

**Comment by hoadlck** [comment]
Can you try it now with the latest content on master (version 0.10.0)? In #471, I placed a limit on the number of threads that can be allocated. And, it did not seem to make any difference on performance.

Other people have been having other symptoms, but I wonder if this bug may have been what you have been seeing.

**Comment by hoadlck** [comment]
Closing this issue out, as I believe it was involved in the earlier versions of Sherlock that did not place any limit on the number of workers when doing requests.  As more sites were added, it would bring any computer to its (virtual) knees.
