### ISSUE TITLE
Duolingo and Paypal seems to match every username 

### ISSUE THREAD

**Issue by alexwennerberg** [sherlock-project/sherlock#314]
Every username I've tried matches duolingo and PayPal, even ones that do not exist. Reproduce this by running Sherlock for any username and you'll always see Duolingo and Paypal accounts.

Using commit 6914c308a36df42929b31d0ee20cdb8dc53a1dfa

**Comment by hoadlck** [comment]
I fixed a problem on Paypal, but I do not see a problem on Duolingo.

Here is a check I ran:
```
% python -u sherlock.py --site Duolingo blue

[*] Checking username blue on:
[+] Duolingo: https://www.duolingo.com/blue
% python -u sherlock.py --site Duolingo noonewouldeverusethis7

[*] Checking username noonewouldeverusethis7 on:
[-] Duolingo: Not Found!
```
What did you try?

**Comment by alexwennerberg** [comment]
Looks like it only affects usernames with a length of 15 characters or less:
```
$ python -u sherlock.py --site Duolingo noonewouldever7

[*] Checking username noonewouldever7 on:
[+] Duolingo: https://www.duolingo.com/noonewouldever7
```

**Comment by Rand66** [comment]
On Aug 25, 2019 7:33 PM, "Alex Wennerberg" <notifications@github.com> wrote:

Looks like it only affects usernames with a length of 15 characters or less:

$ python -u sherlock.py --site Duolingo noonewouldever7

[*] Checking username noonewouldever7 on:
[+] Duolingo: https://www.duolingo.com/noonewouldever7

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/sherlock-project/sherlock/issues/314?email_source=notifications&email_token=AMPWCU55RHY74XV4QQFXX53QGMJETA5CNFSM4IPJYSN2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD5C6EVA#issuecomment-524673620>,
or mute the thread

**Comment by LameLemon** [comment]
When checking only Paypal the it seems to work, but when checking all sites together it doesn't. The following username `wjewekjflkew` does not exist. 

```
$ python3 sherlock.py wjewekjflkew --site paypal
[*] Checking username wjewekjflkew on:
[-] PayPal: Not Found!

$ python3 sherlock.py wjewekjflkew 
[*] Checking username wjewekjflkew on:
[-] ResearchGate: Illegal Username Format For This Site!
**Omitted some websites**
[-] Patreon: Not Found!
[+] PayPal: https://www.paypal.me/wjewekjflkew
[-] Pexels: Not Found!
**Omitted some websites**
[-] segmentfault: Not Found! 
```

The username `blue` does exist and it detects that while checking for Paypal only
```$python3 sherlock.py blue --site paypal
[*] Checking username blue on:
[+] PayPal: https://www.paypal.me/blue
``

Something seems to be wrong while running the Paypal with all the other sites. 

I made sure to `git pull` and I'm running the up to date version on the master branch with `Paypal Fix`.

**Comment by hoadlck** [comment]
I removed PayPal and Duolingo in #342.  If they are not working, then they should not be included.  I did add them in the list of bad sites, so we have them captured in the backlog.

**Comment by hoadlck** [comment]
The sites that are not working were removed in #342.
