### ISSUE TITLE
Sherlock keeps freezing mid-program

### ISSUE THREAD

**Issue by eanstandig41** [sherlock-project/sherlock#357]
Everytime I run Sherlock it goes through about 10-15 websites and then just stops searching. I've reinstalled it twice and this keeps happening.

**Comment by sdushantha** [comment]
@eanstandig41 I just tried it, and it works perfectly fine. I am not really sure what the problem is.

Here are some ideas that came to my mind:
1. Your internet connection might a little slow or if you are using a proxy or a VPN, that could also cause the freezing. 

2. If it is freezing when it is trying to connect to a site, then it might that it takes longer to connect to it due to your country or something.

3. Try using a different username and see if you still get the freezing.

Please do let me know if you were able to fix it. If not, we will try to find a solution :)

**Comment by hoadlck** [comment]
Can you try it now with the latest content on master (version 0.10.0)? In #471, I placed a limit on the number of threads that can be allocated. And, it did not seem to make any difference on performance.
