### ISSUE TITLE
website cash.me always reports as found

### ISSUE THREAD

**Issue by Abhimanyu8** [sherlock-project/sherlock#433]
I have tried 17 usernames, till date and in all of them sherlock finds an account in 'cash.me', all of which are false positives and cash.me does not contain the username found by sherlock on their site .

**Comment by hoadlck** [comment]
I always get a connection error.  I think the site needs to be removed.

**Comment by hoadlck** [comment]
Looks like CashMe changed their site so that a username looks like https://cash.me/$Jenny instead of https://cash.me/jenny.  The 301 redirect was getting interpreted as a success status code, so it is reported as found.

I updated the URL and pushed the change to master.

However, I still get errors connecting more times than not.  Does this work any better?

**Comment by LameLemon** [comment]
I've tried multiple usernames, it looks like the new commit fixed the issue, no errors on my end.

**Comment by Abhimanyu8** [comment]
In my end, i found that the latest commit is still giving this issue, but now the cash.me output looks 
like https://cash.me/$username instead of https://cash.me/username like it did before.

**Comment by LameLemon** [comment]
@Abhimanyu8  Can you give example that produce a false positive please.

**Comment by roopeshvs** [comment]
This is because CashMe does not support the user's country. CashMe most likely uses IP addresses to determine that. Although this can be sorted via using a proxy or VPN, I think a lot of users do not need to and yet receive a false-positive.

I suggest we make Sherlock report CashMe Not Found in countries that do not have CashMe. i.e., report false-negatives instead of false-positives. Will that be an acceptable change?
