### ISSUE TITLE
Does not find Facebook accounts

### ISSUE THREAD

**Issue by aoxhwjfoavdlhsvfpzha** [sherlock-project/sherlock#445]
Sherlock, through termux atleast, fails to find existing Facebook accounts under their usernames.
Haven't tried through a desktop environment as of yet.

**Comment by LameLemon** [comment]
Can I have some examples of the false negatives please.

**Comment by sdushantha** [comment]
Closing this issue as it is inactive. Also the account that was used to submit this issue seems like a throw away account because it was created only a month ago and it was only used to submit this issue, so I don think we will be hearing from them again. But if we do, feel free to reopen this issue :)
