### ISSUE TITLE
Add search "seatracker"

### ISSUE THREAD

**Issue by torerobo** [sherlock-project/sherlock#456]
```
  "seatracker": {
    "errorMsg": "Извините, такого пользователя не существует",
    "errorType": "message",
    "rank": 87536,
    "url": "https://seatracker.ru/profile.php?mode=viewprofile&u={}",
    "urlMain": "https://seatracker.ru/",
    "username_claimed": "blue",
    "username_unclaimed": "noonewouldeverusethis7"
  },

```

**Comment by sdushantha** [comment]
@toddrob99 This site has a problem. When I visit the site, I get this page:
![image](https://user-images.githubusercontent.com/27065646/71121125-1f4fc800-21de-11ea-9069-e7c7ee349e39.png)
I tried with a VPN, and got the same page. Therefore I will not be adding this site to Sherlock.

If you find a fix for this please let me know so that I can add it later :)

**Comment by torerobo** [comment]
Sorry, maybe it was a temporary malfunction or maintenance. Zayt is available and I see no problems, you can see.

![1](https://user-images.githubusercontent.com/35532898/71148892-fced9700-223d-11ea-94d6-f157c74287f4.png)

**Comment by sdushantha** [comment]
@torerobo I am still getting the same error. Could it be that this site only works in Russia?

**Comment by torerobo** [comment]
The site crashes, I also got an error now. In fact, I checked it through vpn Europe was available.

**Comment by torerobo** [comment]
@sdushantha @hoadlck  suggest adding this site. I watched him for a long time. The site is accessible and normal. I checked through different vps.

Check, please

**Comment by sdushantha** [comment]
![Screenshot_20200110-171512_Firefox Preview](https://user-images.githubusercontent.com/27065646/72168103-c9c99e00-33cc-11ea-8cab-56d8241adfeb.png)
@torerobo
