### ISSUE TITLE
Phone number & Emails

### ISSUE THREAD

**Issue by Cvar1984** [sherlock-project/sherlock#475]
Hello, this is very amazing application, but Is there any way to hunt social media account by email or phone number? Because some people have a lot of username. Thanks you.

**Comment by hoadlck** [comment]
Sherlock just looks at public information.  Most sites hide e-mail addresses and phone numbers...because if they did not, then spammers would have yet another source of data.

If you have such personnel information (like a phone number or e-mail address), why not just ask the person about other social media sites they might belong to?
