### ISSUE TITLE
Ranking using site_list.py only works from certain countries

### ISSUE THREAD

**Issue by sdushantha** [sherlock-project/sherlock#610]
Hi,

For some strange reason `site_list.py` seems to be working for some people and not for others. When I run `python3 site_list.py -r`, to update the ranking, all the ranks get set to 0 and I get errors about the XML data that is returned by data.alexa.com. This is because all I am getting is this:
![Screenshot 2020-05-17 at 07 53 41](https://user-images.githubusercontent.com/27065646/82136986-dabf6b80-9813-11ea-938c-5efa1e520bc0.png)

But when I use a VPN and change my location from Norway to Dallas, which is a city in the US, I seem to get the expected response:
![updated](https://user-images.githubusercontent.com/27065646/82137013-10645480-9814-11ea-9840-e2104451a317.png)

From this, we can understand that this API seems to not be working properly in certain countries.

This issue has been seen here:
https://github.com/matomo-org/matomo/issues/13427
https://stackoverflow.com/questions/3676376/fetching-alexa-data#comment87619041_6224304

I personally think, if the ranking does not work for everyone, then it would be best to remove it.

**Comment by hoadlck** [comment]
If we remove this script's access to the Alexa API, then we will have to remove the aspects of Sherlock that use the site ranking.  Is that OK?

I am thinking that if we automate the invocation of this script using GitHub actions, then no one will have to run it on their own computer any more.  Since the GitHub Actions for Sherlock appear to be running in the US, then it will work reliably.

While the script does generally work for me, it still flakes out on some sites.  I think it is because Sherlock has enough sites that it is exceeding the API limits.

**Comment by sdushantha** [comment]
> If we remove this script's access to the Alexa API, then we will have to remove the aspects of Sherlock that use the site ranking. Is that OK?

Yeah I personally think that doing so would be fine because like you mentioned, its flakes out on some sites and that might be because its exceeding the API limits.

So, removing the site ranking would be the best thing to do as it is not stable.

**Comment by sdushantha** [comment]
It seems like it better to remove the site ranking because I tried running `site_list.py` using a VPN, where my location was Los Angeles and I keep getting this response:
```xml
<!-- Need more Alexa data?  Find our APIs here: https://aws.amazon.com/alexa/ -->
```

There is rate limit
