### ISSUE TITLE
Getting stuck at Coroflot

### ISSUE THREAD

**Issue by Fabruk** [sherlock-project/sherlock#644]
Hey guys,
I haven't been able to use this as it get stuck at Coroflot. Does anyone getting the same issue?
Any workaround? I tried to delete and reinstall but issue persists. Running on Kali Linux.
Cheers

**Comment by sdushantha** [comment]
Hi @Fabruk :)

The reason for Sherlock getting stuck at Coroflot could be because of your internet connection because I just ran a fresh install of Sherlock and everything seems to be working smoothly.

**Comment by sdushantha** [comment]
Closing this issue assuming that it has been solved. And I'm not expecting a reply because that account was created on the same day this issue was made, so I assume it's a throw away account.

I know assuming is not good, but that's the only thing I can do in order to clean up the issues in this repo.
