### ISSUE TITLE
Retry the HTTP request again if the connection was rejected.

### ISSUE THREAD

**Issue by Piskuliki0723** [sherlock-project/sherlock#648]
Sometimes an error may occur while searching on the same site: "connection error", and sometimes not. You may need to send a second http request to the same site, and if it fails, then continue the search..

**Comment by YeaToast** [comment]
# MISSING INFO

I need some details if you expect support

1. Which OS are you using?
2. Do you have a firewall blocking certain websites?
3. Does your ISP Block certain websites?

**Comment by Uc207Pr4f57t9-251** [comment]
I met the similar problems too

when I start to search it reported like this:
"A problem occured while checking for an update: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /sherlock-project/sherlock/master/sherlock/sherlock.py (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fe6b792cdf0>: Failed to establish a new connection: [Errno 111] Connection refused'))
ERROR:  Problem while attempting to access data file URL 'https://raw.githubusercontent.com/sherlock-project/sherlock/master/sherlock/resources/data.json':  HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /sherlock-project/sherlock/master/sherlock/resources/data.json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fe6b7912610>: Failed to establish a new connection: [Errno 111] Connection refused'))"

OS:debian kali2020

**Comment by changpro** [comment]
@Uc207Pr4f57t9-251 @Piskuliki0723 
Have a try on accessing "raw.githubusercontent.com", the problem may due to **ISP block or your firewall** if it fails. 
Find the IP address of "raw.githubusercontent.com" in [ipaddress.com](https://www.ipaddress.com/)
Then modify your hosts file with adding a line like this:
`199.232.68.133 raw.githubusercontent.com # github raw`

**Comment by YeaToast** [comment]
> I met the similar problems too
> 
> when I start to search it reported like this:
> "A problem occured while checking for an update: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /sherlock-project/sherlock/master/sherlock/sherlock.py (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fe6b792cdf0>: Failed to establish a new connection: [Errno 111] Connection refused'))
> ERROR: Problem while attempting to access data file URL 'https://raw.githubusercontent.com/sherlock-project/sherlock/master/sherlock/resources/data.json': HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /sherlock-project/sherlock/master/sherlock/resources/data.json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fe6b7912610>: Failed to establish a new connection: [Errno 111] Connection refused'))"
> 
> OS:debian kali2020

Ok, You use Linux. Standard procedure for Sherlock. Make sure you have Git installed. If you want to update the data.json file, you just have to `git pull` in ste directory where Sherlock resides. That way data.json is always updated. Also, does raw.githubusercontent.com work for you in the browser? If so, then maybe your internet (or firewall for the record) is really bad. What you're going to do (if git pull won't work) is just download the file and place it in there, no biggie.

**Comment by sdushantha** [comment]
I have ran Sherlock from multiple IP's from different location around the world using a VPN and can confirm that I do not get any connection error. It only occurs when a site is blocked in a country. So doing multiple request would not help and would be a waste of resources
