### ISSUE TITLE
shoudn't the program close once it has finished all the searches?

### ISSUE THREAD

**Issue by furher023** [sherlock-project/sherlock#649]
It just stays open, and on pressing ctrl+c gives callback error

**Comment by sdushantha** [comment]
Hey @furher023!

It seems to working fine on my end:
![image](https://user-images.githubusercontent.com/27065646/85203255-ba9c3400-b30c-11ea-8e4c-4a999cedf6ff.png)

Are you sure that Sherlock finished its searches? Or is it just taking a long time to find a site? Because I feel like it could be that Sherlock might be taking a long time on a certain site due to your location.

**Comment by furher023** [comment]
How much time, do you suggest? I had a very strong internet connection, ans waited for about 10 mins, should i share the error which I got after pressing Ctrl+C? @sdushantha

**Comment by sdushantha** [comment]
@sdushantha Yes, sharing the error might be helpful

**Comment by furher023** [comment]
I think there was some problem connecting, working fine now.
