### ISSUE TITLE
hangs

### ISSUE THREAD

**Issue by elazzzzyy** [sherlock-project/sherlock#677]
hangs on zhihu and doesn't move.

**Comment by sdushantha** [comment]
@elazzzzyy Are you using the latest commit of Sherlock? Zomato was the site which was creating the hang, and I removed in this commit: db878ab5f993c4bb062a7ac847ab7c56682a0293

I just tested out Sherlock with a clean download, and it works perfectly.

**Comment by elazzzzyy** [comment]
Not sure if anything correlates but same happened to my url fuzzer. reinstalled and it works but this is a pain

**Comment by sdushantha** [comment]
@elazzzzyy So is everything fixed? May I close this issue?

**Comment by elazzzzyy** [comment]
No

**Comment by sdushantha** [comment]
@elazzzzyy Have you tried reinstalling Sherlock with the latest version?

**Comment by elazzzzyy** [comment]
Yes

**Comment by sdushantha** [comment]
Ive tried using Sherlock from my local computer and different servers which are located in different countries and they seems to be working perfectly. I am pretty sure that you are having issues due to you internet connection. 
I'll be closing this issue because this is more of a environment issue and not an issue related to Sherlock
