### ISSUE TITLE
Cannot use Sherlock on iOS app Pyto

### ISSUE THREAD

**Issue by YeaToast** [sherlock-project/sherlock#679]
I cannot clone the repo, nor can I install from the requirements.txt. Somebody please help, I also cannot find any git2zip file converters

**Comment by sdushantha** [comment]
> Cannot use Sherlock on iOS app Pyto

Sherlock was never meant to support Pyto and we wont be planning on creating support for it. I would recomend you to use Pythonista instead because it allows you use `pip` to install modules through a terminal like application called [StaSh](https://github.com/ywangd/stash). I think it also has `git` if I remember correctly. Just so you know, **Sherlock might not work on Pythonista either**, but I think there is a higher chance for it to work because of the many features it has.

> I also cannot find any git2zip file converters

There is no need to convert a git repo to a zip because you can directly download the zipped repo from GitHub:
![image](https://user-images.githubusercontent.com/27065646/88507206-30668000-cfdc-11ea-8696-8cd92ec719db.png)

----

Closing this because it is not a problem in Sherlock.

**Comment by YeaToast** [comment]
Pyto has PIP - you just have to look for it.
