### ISSUE TITLE
'git' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by termashacker69** [sherlock-project/sherlock#686]
yeah please helpit just says that as soon as i try the first command

**Comment by YeaToast** [comment]
What OS are you running?

**Comment by rodrigograca31** [comment]
This is not a valid issue. 

You don't seem to have `git` installed. 
This could be solved with a google search. has nothing to do with this project.

Please close the issue

**Comment by sdushantha** [comment]
@rodrigograca31 I find it difficult to close and issue without the person finding a solution as it seems rude. I have thought about creating issue templates for this repo, but cant seem to create a good one. I tried using [youtube-dl's issue templates](https://github.com/ytdl-org/youtube-dl/issues/new/choose) as a reference but didn't do much help because I dont feel like they fit this project well.


---

Closing this issue as it is not related to Sherlock, but is a issue with the user's environment.

**Comment by rodrigograca31** [comment]
@sdushantha I completely understand.
But we got to be real. The issue was not related at all.

When it comes to the issue template here is [a repo with a few examples](https://github.com/stevemao/github-issue-templates).

May I suggest one of the following:
https://github.com/stevemao/github-issue-templates/blob/master/simple/ISSUE_TEMPLATE.md
https://github.com/stevemao/github-issue-templates/blob/master/bugs-only/ISSUE_TEMPLATE.md

**Comment by sdushantha** [comment]
@rodrigograca31 I finally created the issue templates! :) 
Check them out here: #832

**Comment by rodrigograca31** [comment]
Nice. well done.
looks good @sdushantha
