### ISSUE TITLE
YandexCollection false positives

### ISSUE THREAD

**Issue by philku** [sherlock-project/sherlock#714]
When using the application, YandexCollection reports a find for all usernames. 

I am testing from the USA.

Sample output: 
```shell
 py sherlock.py fsda89fasdfj8fdsaf7ewrj843a4rq3w

[*] Checking username fsda89fasdfj8fdsaf7ewrj843a4rq3w on:
[-] Flightradar24: Illegal Username Format For This Site!
...
[-] Xbox Gamertag: Not Found!
[+] YandexCollection: https://yandex.ru/collections/user/fsda89fasdfj8fdsaf7ewrj843a4rq3w/
[-] YouNow: Not Found!
...
```

**Comment by sdushantha** [comment]
This issue has been fixed in commit d32794f. I removed it from the `data.json` because YandexCollection now presents us with a rechapta which prevents us from checking for usernames. If there is a fix for this in the future, we will of course add it back.

Thank you for letting us know about this false positive 👍
