### ISSUE TITLE
OS connection error

### ISSUE THREAD

**Issue by Franceshe** [sherlock-project/sherlock#724]
Wonder anyone ran into the same error while experimenting with this project as following:
`
➜  sherlock git:(master) python3 sherlock allenturing
A problem occured while checking for an update: ('Connection aborted.', OSError(0, 'Error'))
ERROR:  Problem while attempting to access data file URL 'https://raw.githubusercontent.com/sherlock-project/sherlock/master/sherlock/resources/data.json':  ('Connection aborted.', OSError(0, 'Error'))
`

Not sure where such error come from and I already verified my connection to desired path is valid as following:

`
➜  sherlock git:(master) ping https://raw.githubusercontent.com/sherlock-project/sherlock/master/sherlock/resources/data.json
PING https://raw.githubusercontent.com/sherlock-project/sherlock/master/sherlock/resources/data.json (198.18.3.142): 56 data bytes
`
`
64 bytes from 198.18.3.142: icmp_seq=0 ttl=63 time=0.097 ms
`
I also run through all the unit test and rechecked the process of package installation, maybe incompatible packages could be cause of error.

Instead, i simply switch to docker now.

**Comment by sdushantha** [comment]
@Franceshe What OS are you using?

**Comment by Franceshe** [comment]
> @Franceshe What OS are you using?

@sdushantha  I am using Mac OS Mojave Version 10.14.6.

**Comment by sdushantha** [comment]
@Franceshe That is very strange because I am also on macOS, but Sherlock is working perfectly. Not that it should matter, but I am using Catalina 10.15.2

I have had really bad experience with Python on macOS. I have many issues with SSL, pip not working properly, and some issues with external modules. 

This is an environment issue, and does nothing to do with Sherlock. If Docker works for you, then I would honestly stick with that.

**Comment by abhishekkm17** [comment]
Hi,

I have the same problem. Please help me to resolve.
