### ISSUE TITLE
/usr/bin/python3: No module named pip

### ISSUE THREAD

**Issue by Anand643-eng** [sherlock-project/sherlock#788]
please fix this issue

**Comment by foo2rama** [comment]
pip is an addition to python that allows for automated installation of modules/packages.  Please google how to install pip on your OS.

**Comment by IrishAce** [comment]
I had this same issue. 

1. First, make sure you update your Kali, or upgrade to 2020.3
          [https://www.kali.org/docs/general-use/updating-kali/](url)
2. Confirm you have the latest version of Python3
$ python -V
3. Install pip3.
$ sudo apt install python3-pip

I actually performed a complete re-install since I had other system issues as well. Then when I installed Sherlock per instruction here on GitHub, it worked perfectly fine.

Good luck!

**Comment by linehammer** [comment]
Pip is a python packaging module that helps us too install python libraries. To install python libraries/modules ,you need to [install pip](http://net-informations.com/python/iq/pip.htm)-

    sudo apt-get install python-setuptools
    sudo easy_install pip
    sudo apt-get update
    which pip //to check pip install or not
    pip install requests

Upgrade pip

python -m pip install --upgrade pip
