### ISSUE TITLE
Website rate limiting leads to False Positives

### ISSUE THREAD

**Issue by h20190563** [sherlock-project/sherlock#816]
![bug1](https://user-images.githubusercontent.com/73378474/97347279-93ed9b80-18b2-11eb-867f-feb8c97ae115.PNG)
As we can see in the above snapshot, 
BitCoinForum, 
EyeEm, 
HackerNews, 
Tinder, 
VirusTotal, 
Wattpad, 
forum_guns 
display urls for the account name " noonewlouduse" but actually this username don't exist for them.

**Comment by pkubiak** [comment]
Can't reproduce, I only see four false positives as described in https://github.com/sherlock-project/sherlock/issues/813

**Comment by darvell** [comment]
There are issues where if you're doing it often and some sites will return essentially status codes as a form of rate limiting but if it's looking for a message, it'll consider it 'passed'. I think maybe it would be good if 403's and >500's were automatically considered a fail rather than a pass. I can see why this happens since the whole error styles are just a big switch (ok if/elif) and can't support multiple types of failures.

**Comment by h20190563** [comment]
Yes, what @darvell suggested is actually happening. @pkubiak if you query with that username multiple times, you will be able to reproduce the same.

**Comment by pkubiak** [comment]
@h20190563 Sure, but it is not the fault of configuration of individual sites, but more the way how sherlock handle rate limits errors (403, >500 as mentioned by @darvell). Maybe the better title for that issue would be `Website rate limiting leads to False Positives`?

**Comment by h20190563** [comment]
@pkubiak thanks! I have changed the title.

**Comment by lostnco1** [comment]
@h20190563 Im new at this but what can i do to contribute that may close this issue?

**Comment by darvell** [comment]
https://github.com/sherlock-project/sherlock/pull/852
ez. enjoy :)

**Comment by sdushantha** [comment]
The sites mentioned in this issue have been dealt with and Sherlock no longer returns false positives :)
