### ISSUE TITLE
How about find user when their name have space like X X

### ISSUE THREAD

**Issue by BobNoobYT** [sherlock-project/sherlock#884]
## Checklist

- [x] I'm asking a question regarding Sherlock
- [x] My question is not a tech support question.

**We are not your tech support**. 
If you have questions related to `pip`, `git`, or something that is not related to Sherlock, please ask them on [StackOverflow](https://stackoverflow.com/) or [r/learnpython](https://www.reddit.com/r/learnpython/)

## Question

ASK YOUR QUESTION HERE
Please answer my title above

**Comment by sdushantha** [comment]
Usernames tend to not have spaces. Sherlock won't be supporting usernames with spaces

**Comment by hoadlck** [comment]
While it is true that usernames would not normally have spaces, Sherlock would support them if they did.  One just needs to quote the username on the command line so that the shell would pass the username to Sherlock.  So, something like "X X" would work.  Or, "X%20X" might also work (depending on how the site accepts queries).

**Comment by sdushantha** [comment]
> While it is true that usernames would not normally have spaces, Sherlock would support them if they did

My bad, I was thinking about actual display names. Thats why I said that sherlock won't be supporting them but I obviously used the wrong words.
