### ISSUE TITLE
WhatsMyName

### ISSUE THREAD

**Issue by WebBreacher** [sherlock-project/sherlock#97]
Neat project and fast too! Love it! Just in case you want more site signatures, check out my similar tool over at https://github.com/webbreacher/whatsmyname. JSON file has the site info which may or may not be helpful...like I said, we have similar projects.

**Comment by hoadlck** [comment]
Is this parallel evolution? Or did @sdushantha look at your project and get inspired?

The ```--site``` option was what I was just proposing to add to Sherlock in another issue.  And, the storing of valid/invalid user names in the JSON file was what I was thinking to do in order to allow the testing to work better.  It looks like your Project has been out there for a while.  While Sherlock has many sites, I am concerned about false positives.  We don't have good testing yet.

But, your project has been around for much longer.  October 2015 was when it started?  We definitely need to keep in touch since our projects are so similar. 

Thanks for letting us know. :)

**Comment by sdushantha** [comment]
> Is this parallel evolution? Or did @sdushantha look at your project and get inspired?

It must be, because I have never seen project :)

**Comment by crock** [comment]
@WebBreacher @hoadlck  I also have a similar project https://github.com/checker/cli and a REST API variant as well as https://github.com/checker/api

**Comment by WebBreacher** [comment]
@crock I've done this already in Recon-ng's multi-threaded Profiler module and Steve Micallef did this in the Spiderfoot "Accounts" module. They take the JSON file and then run several loops on it against as many user names as their databases contain. For details on Profiler, check out https://webbreacher.com/2014/12/11/recon-ng-profiler-module/

**Comment by irazasyed** [comment]
How about merging the two? Just the databases.
